/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PricingIndexRouteImport } from './routes/pricing.index'
import { Route as ServicesToursRouteImport } from './routes/services.tours'
import { Route as ServicesPointToPointRouteImport } from './routes/services.point-to-point'
import { Route as ServicesHourlyRouteImport } from './routes/services.hourly'
import { Route as ServicesAirportRouteImport } from './routes/services.airport'
import { Route as PricingToursRouteImport } from './routes/pricing.tours'
import { Route as PricingPointToPointRouteImport } from './routes/pricing.point-to-point'
import { Route as PricingHourlyRouteImport } from './routes/pricing.hourly'
import { Route as PricingAirportRouteImport } from './routes/pricing.airport'

const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingIndexRoute = PricingIndexRouteImport.update({
  id: '/pricing/',
  path: '/pricing/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesToursRoute = ServicesToursRouteImport.update({
  id: '/services/tours',
  path: '/services/tours',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPointToPointRoute = ServicesPointToPointRouteImport.update({
  id: '/services/point-to-point',
  path: '/services/point-to-point',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesHourlyRoute = ServicesHourlyRouteImport.update({
  id: '/services/hourly',
  path: '/services/hourly',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAirportRoute = ServicesAirportRouteImport.update({
  id: '/services/airport',
  path: '/services/airport',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingToursRoute = PricingToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => PricingRoute,
} as any)
const PricingPointToPointRoute = PricingPointToPointRouteImport.update({
  id: '/point-to-point',
  path: '/point-to-point',
  getParentRoute: () => PricingRoute,
} as any)
const PricingHourlyRoute = PricingHourlyRouteImport.update({
  id: '/hourly',
  path: '/hourly',
  getParentRoute: () => PricingRoute,
} as any)
const PricingAirportRoute = PricingAirportRouteImport.update({
  id: '/airport',
  path: '/airport',
  getParentRoute: () => PricingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/fleet': typeof FleetRoute
  '/pricing/airport': typeof PricingAirportRoute
  '/pricing/hourly': typeof PricingHourlyRoute
  '/pricing/point-to-point': typeof PricingPointToPointRoute
  '/pricing/tours': typeof PricingToursRoute
  '/services/airport': typeof ServicesAirportRoute
  '/services/hourly': typeof ServicesHourlyRoute
  '/services/point-to-point': typeof ServicesPointToPointRoute
  '/services/tours': typeof ServicesToursRoute
  '/pricing/': typeof PricingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/fleet': typeof FleetRoute
  '/pricing/airport': typeof PricingAirportRoute
  '/pricing/hourly': typeof PricingHourlyRoute
  '/pricing/point-to-point': typeof PricingPointToPointRoute
  '/pricing/tours': typeof PricingToursRoute
  '/services/airport': typeof ServicesAirportRoute
  '/services/hourly': typeof ServicesHourlyRoute
  '/services/point-to-point': typeof ServicesPointToPointRoute
  '/services/tours': typeof ServicesToursRoute
  '/pricing': typeof PricingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/fleet': typeof FleetRoute
  '/pricing/airport': typeof PricingAirportRoute
  '/pricing/hourly': typeof PricingHourlyRoute
  '/pricing/point-to-point': typeof PricingPointToPointRoute
  '/pricing/tours': typeof PricingToursRoute
  '/services/airport': typeof ServicesAirportRoute
  '/services/hourly': typeof ServicesHourlyRoute
  '/services/point-to-point': typeof ServicesPointToPointRoute
  '/services/tours': typeof ServicesToursRoute
  '/pricing/': typeof PricingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/fleet'
    | '/pricing/airport'
    | '/pricing/hourly'
    | '/pricing/point-to-point'
    | '/pricing/tours'
    | '/services/airport'
    | '/services/hourly'
    | '/services/point-to-point'
    | '/services/tours'
    | '/pricing/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/fleet'
    | '/pricing/airport'
    | '/pricing/hourly'
    | '/pricing/point-to-point'
    | '/pricing/tours'
    | '/services/airport'
    | '/services/hourly'
    | '/services/point-to-point'
    | '/services/tours'
    | '/pricing'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/fleet'
    | '/pricing/airport'
    | '/pricing/hourly'
    | '/pricing/point-to-point'
    | '/pricing/tours'
    | '/services/airport'
    | '/services/hourly'
    | '/services/point-to-point'
    | '/services/tours'
    | '/pricing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FleetRoute: typeof FleetRoute
  ServicesAirportRoute: typeof ServicesAirportRoute
  ServicesHourlyRoute: typeof ServicesHourlyRoute
  ServicesPointToPointRoute: typeof ServicesPointToPointRoute
  ServicesToursRoute: typeof ServicesToursRoute
  PricingIndexRoute: typeof PricingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing/': {
      id: '/pricing/'
      path: '/pricing'
      fullPath: '/pricing/'
      preLoaderRoute: typeof PricingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/tours': {
      id: '/services/tours'
      path: '/services/tours'
      fullPath: '/services/tours'
      preLoaderRoute: typeof ServicesToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/point-to-point': {
      id: '/services/point-to-point'
      path: '/services/point-to-point'
      fullPath: '/services/point-to-point'
      preLoaderRoute: typeof ServicesPointToPointRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/hourly': {
      id: '/services/hourly'
      path: '/services/hourly'
      fullPath: '/services/hourly'
      preLoaderRoute: typeof ServicesHourlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/airport': {
      id: '/services/airport'
      path: '/services/airport'
      fullPath: '/services/airport'
      preLoaderRoute: typeof ServicesAirportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing/tours': {
      id: '/pricing/tours'
      path: '/tours'
      fullPath: '/pricing/tours'
      preLoaderRoute: typeof PricingToursRouteImport
      parentRoute: typeof PricingRoute
    }
    '/pricing/point-to-point': {
      id: '/pricing/point-to-point'
      path: '/point-to-point'
      fullPath: '/pricing/point-to-point'
      preLoaderRoute: typeof PricingPointToPointRouteImport
      parentRoute: typeof PricingRoute
    }
    '/pricing/hourly': {
      id: '/pricing/hourly'
      path: '/hourly'
      fullPath: '/pricing/hourly'
      preLoaderRoute: typeof PricingHourlyRouteImport
      parentRoute: typeof PricingRoute
    }
    '/pricing/airport': {
      id: '/pricing/airport'
      path: '/airport'
      fullPath: '/pricing/airport'
      preLoaderRoute: typeof PricingAirportRouteImport
      parentRoute: typeof PricingRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FleetRoute: FleetRoute,
  ServicesAirportRoute: ServicesAirportRoute,
  ServicesHourlyRoute: ServicesHourlyRoute,
  ServicesPointToPointRoute: ServicesPointToPointRoute,
  ServicesToursRoute: ServicesToursRoute,
  PricingIndexRoute: PricingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
